version: '3.9'

services:
  docker-frontend:
    build:
      context: stock-price-tracker
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./stock-price-tracker/src:/frontend/src:delegated
    command: ng serve --host 0.0.0.0 --poll 2000
