# Use the official Node.js image with the specified version
FROM node:20

# Directory for our application
ARG WORK_DIR=/frontend

# Set the environment variable PATH to include the node_modules binaries
# This is necessary to make the Angular CLI executable (ng) available globally
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

# Create a new folder inside the frontend
RUN mkdir ${WORK_DIR}

# Set the working directory to the specified path
WORKDIR ${WORK_DIR}

# Copy package.json and package-lock.json to the working directory
COPY package.json ${WORK_DIR}
COPY package-lock.json ${WORK_DIR}

# Install the Angular CLI globally
RUN npm install @angular/cli

# Install dependencies based on package.json
RUN npm install

# Copy the entire content of the current directory to the working directory
COPY . ${WORK_DIR}

# Expose port 4200 (the default port for Angular applications)
EXPOSE 4200

# Set the default command to run when the container starts
CMD ng serve --host 0.0.0.0
