name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master repo
        uses: actions/checkout@v2
        with:
          repository: Stock-Price-Tracker
          ref: master
          path: master

      - name: Build Main
        run: | 
          # Replace with your actual build commands for the main project
          cd master
          npm install
          npm run build
        working-directory: ./master

      - name: Publish
        run: |
          # Replace with your actual publish commands for the main project
          echo "Publishing main project"
        working-directory: ./master

  angular:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout angular repo
        uses: actions/checkout@v2
        with:
          repository: Github_Actions_build_repo_test
          path: master

      - name: Install Dependencies
        run: 
          cd master
          npm ci

      - name: Build Angular
        run: npm run build --prod --base-href='angular' 
          # Replace with your actual build commands for the Angular project
          
        working-directory: .

      - name: Publish
        run: |
          # Replace with your actual publish commands for the Angular project
          echo "Publishing Angular project"
        working-directory: .
