name: Stock-Price-Tracker__build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Linux-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.6, 16.8.0, 18.0.0, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build 
      - run: npm test
        env:
          CI: true

  Windows-build:
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [14.17.6, 16.8.0, 18.0.0, 20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build 
      - run: npm test
        env:
          CI: true
