name: Build and Deploy Angular App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: |
        npm install

    - name: Build Angular app
      run: |
        npm run build:ci

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.email "mahmoud.ghonamie@orascom.com"
        git config user.name "notgonim"

    - name: Copy build to another repository
      run: |
        mkdir deploy
        cp -r dist/* deploy/
        cd deploy
        git add .
        git commit -m "Deploy Angular app"
        git remote add origin https://github.com/notgonim/Github_Actions_build_repo_test.git # Replace with the destination repository URL
        git push --force -u origin master:master # Adjust branch names as needed
