name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./stock-price-tracker  # Set the correct path to your project directory

      - name: Build Angular Project
        run: npm run build
        working-directory: ./stock-price-tracker  # Set the correct path to your project directory

      - name: Run Tests
        run: npm test
        working-directory: ./stock-price-tracker  # Set the correct path to your project directory
