name: workflow name

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        working-directory: ./src  # Adjust the path to match your project structure

      - name: Build
        run: npm run build:ci
        working-directory: ./src  # Adjust the path to match your project structure

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: ./src/dist

      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_coverage
          path: ./src/coverage

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: deploy_dist

      - name: Clone destination repository
        run: |
          git config --global user.email "mahmoud.ghonamie@orascom.com"
          git config --global user.name "notgonim"
          git clone https://notgonim:${{ secrets.GITHUB_TOKEN }}@github.com/notgonim/Github_Actions_build_repo_test.git
        working-directory: .

      - name: Copy build to destination repository
        run: cp -r ./deploy_dist/* ./Github_Actions_build_repo_test
        working-directory: .

      - name: Commit and push changes
        run: |
          cd Github_Actions_build_repo_test
          git add .
          git commit -m "Add build files"
          git push origin master
