name: workflow name

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate SSH key
        run: |
          mkdir -p ~/.ssh
          ssh-keygen -t rsa -b 4096 -C "your_email@example.com" -f ~/.ssh/id_rsa -N ""

      - name: Add SSH key to SSH agent
        run: eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa

      - name: Configure Git to use SSH
        run: git config --global core.sshCommand "ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no"

      - name: Use Node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm ci
        working-directory: .  # Adjust the path to match your project structure

      - name: Build
        run: npm run build:ci
        working-directory: .  # Adjust the path to match your project structure

      - name: Debug Directory Structure
        run: ls -R ./src
        working-directory: .

      - name: Archive build
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: ./dist  # Adjust the path to match your project structure

      - name: Archive code coverage result
        if: success()
        uses: actions/upload-artifact@v2
        with:
      .    name: deploy_coverage
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: deploy_dist
          path: ./dist  # Adjust the path to match your desired location

      - name: Clone destination repository
        run: |
          git config --global user.email "mahmoud.ghonamie@orascom.com"
          git config --global user.name "notgonim"
          git clone https://notgonim:${{ secrets.WORKFLOWPASSWORD }}@github.com/notgonim/Github_Actions_build_repo_test.git
        working-directory: .

      - name: Debug Destination Directory Structure
        run: ls -R ./Github_Actions_build_repo_test
        working-directory: .

      - name: Copy build to destination repository
        run: |
          [ -d "./dist" ] && cp -r ./dist/* ./Github_Actions_build_repo_test
        working-directory: .

      - name: Commit and push changes
        run: |
          cd Github_Actions_build_repo_test
          git add .
          git commit -m "Add build files"
          git remote add origin_with_token git@github.com:notgonim/Github_Actions_build_repo_test.git
          git push origin_with_token master


